definitions:
  models.ClientCreate:
    properties:
      company_id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
    type: object
  models.CompanyService:
    properties:
      company_id:
        type: string
      duration:
        type: integer
      guid:
        type: string
      price:
        type: integer
      title:
        type: string
    type: object
  models.CompanyServiceCreate:
    properties:
      company_id:
        type: string
      duration:
        type: integer
      price:
        type: integer
      title:
        type: string
    type: object
  models.CompanyServices:
    properties:
      count:
        type: integer
      services:
        items:
          $ref: '#/definitions/models.CompanyService'
        type: array
    type: object
  models.CreateOrder:
    properties:
      client_id:
        type: string
      company_id:
        type: string
      employee_id:
        type: string
      order_date:
        type: string
      services:
        items:
          type: string
        type: array
      start_time:
        type: string
    type: object
  models.Employee:
    properties:
      company_id:
        type: string
      description:
        type: string
      first_name:
        type: string
      graph_end_time:
        type: string
      graphStartTime:
        type: string
      guid:
        type: string
      last_name:
        type: string
      position:
        type: string
    type: object
  models.EmployeeCreate:
    properties:
      company_id:
        type: string
      description:
        type: string
      first_name:
        type: string
      graph_end_time:
        type: string
      graphStartTime:
        type: string
      last_name:
        type: string
      position:
        type: string
    type: object
  models.EmployeeList:
    properties:
      count:
        type: integer
      employees:
        items:
          $ref: '#/definitions/models.Employee'
        type: array
    type: object
  models.ListOrders:
    properties:
      count:
        type: integer
      orders:
        items:
          $ref: '#/definitions/models.Order'
        type: array
    type: object
  models.Order:
    properties:
      client_contact:
        type: string
      client_fullname:
        type: string
      employee_fullname:
        type: string
      end_time:
        type: string
      order_date:
        type: string
      order_id:
        type: string
      services:
        items:
          type: string
        type: array
      start_time:
        type: string
      total_price:
        type: string
    type: object
  models.ResponseError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  models.SuccessModel:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/client:
    post:
      consumes:
      - application/json
      description: API for creating clients
      parameters:
      - description: company-service
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.ClientCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Create Company Client
      tags:
      - client
  /v1/clients:
    get:
      consumes:
      - application/json
      description: API for get list of clients
      parameters:
      - description: company_id
        in: query
        name: company_id
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      - description: page
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CompanyServices'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: List Clients
      tags:
      - client
  /v1/company-service:
    get:
      consumes:
      - application/json
      description: API for get list company_services
      parameters:
      - description: company_id
        in: query
        name: company_id
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      - description: page
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CompanyServices'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: List Company Services
      tags:
      - company-service
    post:
      consumes:
      - application/json
      description: API for create company-service
      parameters:
      - description: company-service
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.CompanyServiceCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Create Company Service
      tags:
      - company-service
  /v1/employee:
    get:
      consumes:
      - application/json
      description: API for get list employeeslsls
      parameters:
      - description: company_id
        in: query
        name: company_id
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      - description: page
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EmployeeList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: List Employee
      tags:
      - employee
    post:
      consumes:
      - application/json
      description: API for creating client
      parameters:
      - description: employee
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.EmployeeCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Create Employee
      tags:
      - employee
  /v1/employee/{employee_id}:
    get:
      consumes:
      - application/json
      description: API for getting single Employee
      parameters:
      - description: company_id
        in: query
        name: company_id
        required: true
        type: string
      - description: guid
        in: path
        name: employee_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EmployeeList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Get Employee By ID
      tags:
      - employee
  /v1/order:
    post:
      consumes:
      - application/json
      description: API for creating orders
      parameters:
      - description: order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.CreateOrder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Create Order
      tags:
      - order
  /v1/orders:
    get:
      consumes:
      - application/json
      description: API for get list orders
      parameters:
      - description: company_id
        in: query
        name: company_id
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      - description: page
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListOrders'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: List Orders
      tags:
      - order
swagger: "2.0"
